# docker-compose.test.yml
# Test environment setup
version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: healthapp-postgres-test
    environment:
      POSTGRES_DB: healthapp_test
      POSTGRES_USER: healthapp_user
      POSTGRES_PASSWORD: secure_pg_password
    ports:
      - "5434:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U healthapp_user -d healthapp_test"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7.4-alpine
    container_name: healthapp-redis-test
    command: redis-server --appendonly yes --requirepass secure_redis_password
    ports:
      - "6380:6379"
    volumes:
      - redis_test_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_test_data:
    driver: local
  redis_test_data:
    driver: local

networks:
  default:
    name: healthapp-test-network
    driver: bridge
